// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMbOVPGXDVL8-2Ji7LCYsc2KiuPzGyU3M',
    appId: '1:560093829390:web:371b6d8b1fb97132be9f5f',
    messagingSenderId: '560093829390',
    projectId: 'tekmob---prak10',
    authDomain: 'tekmob---prak10.firebaseapp.com',
    storageBucket: 'tekmob---prak10.appspot.com',
    measurementId: 'G-DVR9CZM266',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkq7ZbtbeTsgyBKAn2G_Z4TILCzmRD1iE',
    appId: '1:560093829390:android:fbee5f55472fd442be9f5f',
    messagingSenderId: '560093829390',
    projectId: 'tekmob---prak10',
    storageBucket: 'tekmob---prak10.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALi8Hy2U0XwZ7INiSQ8vzRK4o7J3OoV9Y',
    appId: '1:560093829390:ios:52b09e3def95a8a6be9f5f',
    messagingSenderId: '560093829390',
    projectId: 'tekmob---prak10',
    storageBucket: 'tekmob---prak10.appspot.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALi8Hy2U0XwZ7INiSQ8vzRK4o7J3OoV9Y',
    appId: '1:560093829390:ios:52b09e3def95a8a6be9f5f',
    messagingSenderId: '560093829390',
    projectId: 'tekmob---prak10',
    storageBucket: 'tekmob---prak10.appspot.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
